"""empty message

Revision ID: 976589145334
Revises: f7cd9e15331e
Create Date: 2024-05-30 15:09:42.868943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976589145334'
down_revision = 'f7cd9e15331e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('item_quantity')

    # ### end Alembic commands ###
